apiVersion: ctl.provenance.com/v1
kind: ProvenanceDeployment
metadata:
  name: frontend-apps
  namespace: apis
  labels:
    pd: frontend-apps
spec:
  selector:
    matchLabels:
      pd: frontend-apps
  template:
    metadata:
      labels:
        pd: frontend-apps
    spec:
      kong:
        enabled: true
        services:
          - name: frontend-apps
            proxy:
              path: /
            route:
              path: /
              strip_path: true
              preserve_host: false
            jwt:
              enabled: true
              isFrontEnd: true
              isCookieAuth: true
      deployment:
        port: 80
        replicas:
          prod: 1
          test: 1
        isFrontEnd: true
        image:
          prod: us.gcr.io/figure-production/frontend-apps:latest
          test: us.gcr.io/figure-development/frontend-apps:latest
        networkPolicy:
          enabled: true
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        readinessProbe:
          path: /
          periodSeconds: 3
          initialDelaySeconds: 30
        livenessProbe:
          path: /
          periodSeconds: 3
          initialDelaySeconds: 100